#!/usr/bin/env php
<?php

use App\Commands\Play;
use App\Deck;
use Symfony\Component\Console\Application;

require __DIR__ . '/vendor/autoload.php';

$application = new Application();
$application->add(new Play(new Deck));
$application->setDefaultCommand('play', true)->run();
